SawSimE/ShinhanHack_SawSim

Frontend/App.js

#2 [FEAT] : 프엔 브랜치 안뜸 이슈

---

Frontend/src/Api/Api.js
Frontend/src/setupProxy.js

#8 [FEAT] : 로그인 ing

---

Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/Calendar.module.css
Frontend/src/pages/Plan.js
Frontend/src/pages/Plan.module.css

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18uwhzYWNVvz7eUdgsxdL7kEsS4BESCLc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=3j1aQly)
#5 [FEAT] : 일정 null 값 팝업 창 띄우기

#5 [FEAT] : 일정 null 값 팝업 창 띄우기

---

Frontend/src/components/login/TransferOne.js
Frontend/src/components/login/TransferOne.module.css

#8 [FEAT] : 1원 이체 4번

---

Frontend/src/components/login/TransferOne.js
Frontend/src/pages/Login.js
Frontend/src/pages/Login.module.css

#8 [FEAT] : 인증번호 4자리 입력

---

Frontend/src/components/login/TransferOne.js
Frontend/src/pages/MainPage.js

#8 [FEAT] : 로그인 완성

---

Frontend/package-lock.json
Frontend/package.json
Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/PrevCal.js

#5 [FEAT] : 달력 대대적인 수정 완료

---

Frontend/package-lock.json
Frontend/package.json
Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/DailyBudget.js
Frontend/src/components/plan/PrevCal.js
Frontend/src/components/plan/TripDate.js
Frontend/src/components/plan/TripDate.module.css
Frontend/src/pages/Plan.js
Frontend/src/pages/Plan.module.css

#5 [FEAT] : 달력 모달 완성

---

Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/DateList.js
Frontend/src/pages/Plan.js

#46 [REFACTOR] : 날짜별 컴포넌트 리팩토링 전 백업

---

Backend/src/main/java/com/example/backend/domain/plan/controller/PlanController.java
Backend/src/main/java/com/example/backend/domain/plan/dto/PlanDetailResponse.java
Backend/src/main/java/com/example/backend/domain/plan/dto/PlanDetailResponseDto.java
Backend/src/main/java/com/example/backend/domain/plan/dto/PlanListResponseDto.java
Backend/src/main/java/com/example/backend/domain/plan/dto/PlanSaveRequestDto.java
Backend/src/main/java/com/example/backend/domain/plan/entity/Plan.java
Backend/src/main/java/com/example/backend/domain/plan/repository/PlanRepository.java
Backend/src/main/java/com/example/backend/domain/plan/service/PlanService.java

여행 계획 API 개발

---

Frontend/src/App.js
Frontend/src/components/plan/Calendar.css
Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/DateList.js
Frontend/src/pages/Plan.js
Frontend/src/pages/PlanBudget.js

#4 [FEAT] : 달력 모달 css 수정, 예산 추가하기 연결, 날짜별 컴포넌트 css 추후 수정 예정

---

Frontend/src/components/plan/BudgetCreate.js
Frontend/src/components/plan/BudgetCreate.module.css
Frontend/src/components/plan/Calendar.css
Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/bbackup.js
Frontend/src/pages/PlanBudget.js

#4 [FEAT] : 달력 모달 수정 및 예산 추가하기 완료

---

Backend/build.gradle
Backend/src/main/java/com/example/backend/domain/budget/repository/BudgetRepository.java
Backend/src/main/java/com/example/backend/domain/portfolio/controller/PortfolioController.java
Backend/src/main/java/com/example/backend/domain/portfolio/dto/KakaoPlaceSearchResponseDto.java
Backend/src/main/java/com/example/backend/domain/portfolio/dto/PortfolioMapResponseDto.java
Backend/src/main/java/com/example/backend/domain/portfolio/dto/PortfolioRequestDto.java
Backend/src/main/java/com/example/backend/domain/portfolio/dto/PortfolioResponseDto.java
Backend/src/main/java/com/example/backend/domain/portfolio/dto/ShinhanTransactionRequestDto.java
Backend/src/main/java/com/example/backend/domain/portfolio/dto/ShinhanTransactionResponseDto.java
Backend/src/main/java/com/example/backend/domain/portfolio/entity/BudgetOver.java
Backend/src/main/java/com/example/backend/domain/portfolio/entity/Portfolio.java
Backend/src/main/java/com/example/backend/domain/portfolio/entity/Transaction.java
Backend/src/main/java/com/example/backend/domain/portfolio/entity/TransactionHistory.java
Backend/src/main/java/com/example/backend/domain/portfolio/repository/BudgetOverRepository.java
Backend/src/main/java/com/example/backend/domain/portfolio/repository/PortfolioRepository.java
Backend/src/main/java/com/example/backend/domain/portfolio/repository/TransactionRepository.java
Backend/src/main/java/com/example/backend/domain/portfolio/service/PortfolioService.java

여행 포트폴리오 기능 개발 완료

---

Frontend/src/components/plan/DateList.js
Frontend/src/components/plan/SelectedDate.js
Frontend/src/components/plan/TestCalendar.js
Frontend/src/components/planBudget/CreateBudget.js
Frontend/src/components/planBudget/DeleteBudget.js
Frontend/src/pages/Plan.js

#4 [FEAT] : 선택된 일정 관련 수정

---

Frontend/src/components/planBudget/CreateBudget.js
Frontend/src/components/planBudget/CreateBudget.module.css
Frontend/src/components/planBudget/DeleteBudget.js

#4 [FEAT] : 예산 추가, 삭제 css 수정

---

Backend/src/main/java/com/example/backend/domain/analyze/controller/AnalyzeController.java
Backend/src/main/java/com/example/backend/domain/analyze/dto/AnalyzeRequestDto.java
Backend/src/main/java/com/example/backend/domain/analyze/dto/AnalyzeResponseDto.java
Backend/src/main/java/com/example/backend/domain/analyze/service/AnalyzeService.java
Backend/src/main/java/com/example/backend/domain/portfolio/dto/KakaoPlaceSearchResponseDto.java
Backend/src/main/java/com/example/backend/domain/portfolio/service/PortfolioService.java

PortfolioService 메소드 public 변경
KakaoPlaceSearchResponseDto 에서 카테고리 이름 받아오는 변수 추가
Controller, dto, service 개발

여행 지출 분석 API 개발 완료

---

Frontend/src/components/plan/Calendar.css
Frontend/src/components/plan/Calendar.js
Frontend/src/components/planBudget/Create.css
Frontend/src/components/planBudget/CreateBudget.js
Frontend/src/components/planBudget/CreateBudget.module.css
Frontend/src/components/planBudget/DeleteBudget.js
Frontend/src/pages/Plan.js

#69 [FEAT] 예산 추가하기 페이지 구현 중, 추가 및 삭제 버튼 css 완료

---

Frontend/src/components/planBudget/BudgetList.js
Frontend/src/components/planBudget/CreateBudget.js
Frontend/src/pages/PlanBudget.js

#64 [FEAT] : 예산 리스트 페이지 생성, css 수정

---

Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/DateList.js

#4 [FEAT] : Calendar, DateList 로직 수정

---

Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/DateList.js
Frontend/src/components/plan/DateList.module.css
Frontend/src/components/plan/SelectedDate.js
Frontend/src/components/plan/SelectedDate.module.css
Frontend/src/components/plan/backup.js
Frontend/src/components/planBudget/CreateBudget.module.css
Frontend/src/pages/Plan.js

#4 [FEAT] : 날짜별 리스트 띄우기 완료

---

Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/DateList.js
Frontend/src/components/plan/SelectedDate.js

#69 [FEAT] : 예산 추가하기 버튼 연결

---

Frontend/src/App.js
Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/DateList.js
Frontend/src/components/plan/SelectedDate.js
Frontend/src/pages/PlanBudget.js

#69 [FEAT] : 날짜별 예산 연결 중

---

Frontend/src/components/plan/Calendar.js

#69 [FEAT] : 날짜 로컬에 저장

---

Frontend/src/components/plan/Calendar.js
Frontend/src/components/planBudget/CreateBudget.js

#64 [FEAT] : 버튼 css 수정

---

Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/bbackup.js
Frontend/src/components/planBudget/BudgetList.js
Frontend/src/pages/PlanBudget.js
Frontend/src/pages/PlanBudget.module.css

#69 [FEAT] : 뒤로가기 추가

---

Frontend/src/pages/Plan.js
Frontend/src/pages/PlanBudget.js

#69 [FEAT] : css 수정

---

Frontend/src/App.js
Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/DateList.js
Frontend/src/components/plan/SelectedDate.js
Frontend/src/components/plan/backup.js
Frontend/src/components/planBudget/CreateBudget.js
Frontend/src/pages/Plan.js
Frontend/src/pages/PlanDetail.js

#109 [FEAT] : post 요청 및 url 수정

---

Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/DateList.js
Frontend/src/components/plan/SelectedDate.js
Frontend/src/components/plan/bbackup.js
Frontend/src/components/planBudget/CreateBudget.js

#69 [FEAT] 예산 post 요청 성공

---

Frontend/src/components/plan/DateList.js
Frontend/src/components/plan/DateList.module.css
Frontend/src/components/plan/SelectedDate.js
Frontend/src/components/planBudget/CreateBudget.js

#69 [FEAT] : get요청으로 받은 리스트 띄우기 완료

---

Frontend/src/App.js
Frontend/src/components/plan/DateList.js
Frontend/src/components/plan/backup.js
Frontend/src/components/planBudget/DeleteBudget.js
Frontend/src/components/planBudget/EditBudget.js
Frontend/src/components/planBudget/UpdateBudget.module.css
Frontend/src/pages/UpdateBudget.js

#69 [FEAT] : 예산 수정 완료

---

Frontend/src/components/budget/Report.js
Frontend/src/components/plan/DateList.js
Frontend/src/components/planBudget/DeleteBudget.js
Frontend/src/components/planBudget/EditBudget.js

#69 [FEAT] : 예산 삭제 구현 완료

---

Frontend/src/components/budget/Report.js

#69 [FEAT] : 주석 처리 해제

---

Backend/src/main/java/com/example/backend/domain/budget/controller/BudgetController.java
Backend/src/main/java/com/example/backend/domain/budget/dto/BudgetGetResponseDto.java
Backend/src/main/java/com/example/backend/domain/budget/repository/BudgetRepository.java
Backend/src/main/java/com/example/backend/domain/budget/service/BudgetService.java
Backend/src/main/java/com/example/backend/domain/portfolio/repository/TransactionRepository.java
Backend/src/main/java/com/example/backend/domain/portfolio/service/PortfolioService.java

여행 예산 리팩토링

---

Backend/src/main/java/com/example/backend/domain/portfolio/controller/PortfolioController.java
Backend/src/main/java/com/example/backend/domain/portfolio/dto/PortfolioListGetResponseDto.java
Backend/src/main/java/com/example/backend/domain/portfolio/service/PortfolioService.java

Controller portfolioListGet 추가
PortfolioListGetResponseDto 추가
Service portfolioListGet 추가

#118 [FEAT] : 포트폴리오 전체 조회 API 개발

---

Frontend/src/components/main/BalanceSchedule.js

#73 [FIX] : 충돌 해결

---

Frontend/src/components/main/Insurance.js
Frontend/src/components/main/PortBanner.js
Frontend/src/components/main/PortBanner.module.css
Frontend/src/pages/MainPage.js

#73 [FEAT] : 메인 포트폴리오 배너

---

Frontend/package.json
Frontend/src/components/main/BalanceSchedule.js
Frontend/src/components/main/PortBanner.js

#73 [FEAT] : package.json 수정

---

Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/DateList.js
Frontend/src/components/plan/DateList.module.css
Frontend/src/components/plan/SelectedDate.js
Frontend/src/components/plan/SelectedDate.module.css
Frontend/src/components/planBudget/CreateBudget.js
Frontend/src/components/planBudget/CreateBudget.module.css
Frontend/src/components/planBudget/EditBudget.js

#132 [FEAT] 카테고리, 예산 테이블 css 수정

---

Frontend/src/components/budget/Popular.js
Frontend/src/components/budget/Popular.module.css
Frontend/src/components/budget/Report.module.css
Frontend/src/components/cash/CashorOCR.module.css
Frontend/src/components/cash/CreateInPerson.module.css
Frontend/src/components/main/BalanceSchedule.module.css
Frontend/src/components/main/Insurance.module.css
Frontend/src/components/main/PortBanner.js
Frontend/src/components/main/PortBanner.module.css
Frontend/src/components/planBudget/CreateBudget.module.css
Frontend/src/components/popular/PopularSpots.module.css
Frontend/src/components/portfolio/Analysis.module.css
Frontend/src/components/portfolio/PortList.module.css
Frontend/src/pages/Cash.module.css
Frontend/src/pages/Dutch.module.css
Frontend/src/pages/Plan.module.css
Frontend/src/pages/PlanBudget.module.css
Frontend/src/pages/PortfolioDetail.module.css
Frontend/src/pages/Transaction.module.css
Frontend/src/pages/TransactionDetail.module.css

[FIX] : 엄청난 빌드 에러

---

Frontend/src/components/budget/Popular.js
Frontend/src/components/budget/Popular.module.css
Frontend/src/components/budget/Report.module.css
Frontend/src/components/cash/CashorOCR.module.css
Frontend/src/components/cash/CreateInPerson.module.css
Frontend/src/components/login/TransferOne.js
Frontend/src/components/main/BalanceSchedule.module.css
Frontend/src/components/main/Insurance.module.css
Frontend/src/components/main/PortBanner.js
Frontend/src/components/main/PortBanner.module.css
Frontend/src/components/planBudget/CreateBudget.module.css
Frontend/src/components/popular/PopularSpots.module.css
Frontend/src/components/portfolio/Analysis.module.css
Frontend/src/components/portfolio/PortList.module.css
Frontend/src/pages/Cash.module.css
Frontend/src/pages/Dutch.module.css
Frontend/src/pages/Plan.module.css
Frontend/src/pages/PlanBudget.module.css
Frontend/src/pages/PortfolioDetail.module.css
Frontend/src/pages/Transaction.module.css
Frontend/src/pages/TransactionDetail.module.css

[FIX] : 시연용 인증번호 p태그로 띄움

---

Frontend/src/components/plan/DateList.js
Frontend/src/components/planBudget/EditBudget.js
Frontend/src/pages/PlanDetail.js

#132 [FEAT] : 예산 완료시 메인으로 화면 전환 완료

---

Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/DateList.module.css
Frontend/src/components/plan/SelectedDate.js
Frontend/src/components/plan/SelectedDate.module.css
Frontend/src/components/planBudget/CreateBudget.js
Frontend/src/pages/Plan.js
Frontend/src/pages/Plan.module.css
Frontend/src/pages/PlanBudget.js
Frontend/src/pages/PlanBudget.module.css
Frontend/src/pages/PlanBudgetDetail.js
Frontend/src/pages/PlanDetail.js

#131 [FEAT] : plan 페이지 css 수정

---

Frontend/src/components/budget/Report.js
Frontend/src/components/main/BalanceSchedule.js
Frontend/src/components/main/BalanceSchedule.module.css

[FIX] : 예산페이지 그래프 데이터 수정

---

Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/SelectedDate.js

#131 [FEAT] : 날짜 수정

---

Frontend/src/components/main/BalanceSchedule.module.css
Frontend/src/pages/PlanDetail.js

[REFACTOR] : 예산설정 완료버튼 변경

---

Frontend/src/components/plan/Calendar.js
Frontend/src/components/plan/DateList.js
Frontend/src/components/plan/DateList.module.css
Frontend/src/components/planBudget/CreateBudget.js
Frontend/src/components/planBudget/CreateBudget.module.css
Frontend/src/pages/PlanDetail.js
Frontend/src/pages/PlanDetail.module.css

#132 [FEAT] : 예산 추가하는 창, 예산 리스트 css 수정

---

Frontend/public/index.html
Frontend/src/components/budget/Report.js
Frontend/src/components/main/BalanceSchedule.js
Frontend/src/components/main/BalanceSchedule.module.css
Frontend/src/pages/Transaction.js
package-lock.json
package.json

[FEAT] : 거래내역화깅ㄴ

---

Frontend/src/components/plan/DateList.js
Frontend/src/components/plan/SelectedDate.js
Frontend/src/pages/Transaction.css

#132 [FEAT] 예산 추가한 리스트 css 수정, 날짜 변환

---

Frontend/src/components/budget/Report.js
Frontend/src/components/popular/PopularSpots.js
Frontend/src/pages/Transaction.js

[FIX] : 이모저모

---

Frontend/src/components/popular/BackUpPopular.js

#156 [FEAT] : geolocation 사용해서 위도, 경도 받아와서 요청 완료

---

Frontend/src/components/budget/Report.js
Frontend/src/components/main/BalanceSchedule.js
Frontend/src/components/plan/SelectedDate.js

[FIX] : 실시간 분석 그래프

---

Frontend/src/components/budget/Popular.js
Frontend/src/components/budget/Report.js
Frontend/src/components/login/TransferOne.js
Frontend/src/components/main/BalanceSchedule.js
Frontend/src/components/portfolio/Analysis.js
Frontend/src/components/portfolio/PortList.js
Frontend/src/pages/Login.module.css
Frontend/src/pages/Transaction.js
Frontend/src/pages/TransactionDetail.js

[FIX] : 여러 에러 수정

---

Frontend/src/components/portfolio/Analysis.js
Frontend/src/pages/Transaction.js

[FIX] : 에러 수정

---

Frontend/src/components/main/BalanceSchedule.js

[FIX] : 여행 종료 주석 해제
